### ISSUE TITLE
bug: Adds extension to imports from external package sub path

### ISSUE THREAD

**Issue by lenhosseini** [favware/esbuild-plugin-file-path-extensions#101] opened 2024-04-25 13:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Im building a library, lets call it foo, that depends on another library bar. Bar exposes a subpath named "exportA" via its "exports"-key in the package.json. When I import stuff from the subpath "exportA" of bar in foo, e.g.

In foo src code

```ts
import { ... } from "bar/exportA"; 
```

this plugin updates the import in the output to the following

In foo dist

```ts
import { ... } from "bar/exportA.mjs";
```

Then, when using foo in a project, for example a simple vite react project I get the following vite error:

```terminal
✘ [ERROR] Missing "./exportA.mjs" specifier in "bar" package [plugin vite:dep-scan]
```

### Steps To Reproduce

- create a package a that exposes multiple entry points with "exports" in package.json
- import package a in another package b and bundle package b with tsup and `esbuild-plugin-file-path-extensions`
- try to use package b in a vite project 

### Expected behavior

The plugin should only add extensions file imports and not to imports from external packages even if they use sub path exports.

**Comment by favna** [comment] 2024-04-25 19:15
Duplicate of #6 which is still open because I as well as others cannot reproduce it. Please provide a small reproduction repository on that issue.

**Closed by favna** 2024-04-25 19:15 UTC
Labels: bug:unverified
